# brew install
# ------------

brew "neovim"

# brew install --cask
# -------------------

# Browsers
cask "google-chrome"
cask "brave-browser"

# Dev
cask "iterm2"
cask "visual-studio-code"
cask "fork"

# Chat
cask "telegram-desktop"
cask "whatsapp"

# Utilities
cask "appcleaner"
cask "rectangle"
cask "iina"
cask "notion"
cask "figma"
