# brew install
# ------------

brew "neovim"
brew "ni"
brew "mas"

# brew install --cask
# -------------------

# Fonts
cask "font-jetbrains-mono"

# Browsers
cask "google-chrome"
cask "brave-browser"

# Dev
cask "ghostty"
cask "cursor"
cask "fork"
cask "figma"

# Productivity
cask "raycast"
cask "karabiner-elements"

# Notes
cask "craft"
cask "notion"

# Utilities
cask "keepingyouawake"
cask "pearcleaner"

# Misc
cask "chatgpt"
cask "iina"
cask "spotify"
cask "whatsapp"
cask "notion-mail"
cask "raindropio"
cask "stats"
