# brew install
# ------------

brew "neovim"

# brew install --cask
# -------------------

# Fonts
cask "font-jetbrains-mono"

# Browsers
cask "google-chrome"
cask "brave-browser"

# Dev
cask "iterm2"
cask "visual-studio-code"
cask "fork"
cask "figma"
cask "drawio"

# Chat
cask "whatsapp"

# Productivity
cask "loop"
cask "raycast"
cask "karabiner-elements"

# Notes
cask "craft"

# Music
cask "spotify"

# Utilities
cask "appcleaner"
cask "keepingyouawake"
cask "iina"
cask "chatgpt"
